### ISSUE TITLE
why can't start 

### ISSUE THREAD

**Issue by gftyzz12** [EmpireAssatoken/Pancakeswap-Predcition-Winnerbot#1]
when i npm start the bot,
:~/Pancakeswap-Predcition-Bot-new-2023$ npm start
npm ERR! Invalid version: "1.0"

npm ERR! A complete log of this run can be found in:

**Comment by EmpireAssatoken** [comment]
My bad wait 10 minutes :)

**Comment by EmpireAssatoken** [comment]
Thank you for your Help. Now it’s Fixed :)
